DigitalLibrary/DigitalLibrary/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

#import login.views as login_view
import readerCenter.views as readerCenter_view
import search.views as search_view
import participate.views as participate_view
import readerService.views as readerService_view
import librarian.views as librarian_view
import service.views as service_view
import infoCenter.views as infoCenter_view
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve


urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^$', search_view.test, name='indextest'),
    url(r'^login/', include('login.urls',namespace = 'login')),
    url(r'^readerCenter/', include('readerCenter.urls',namespace = 'readerCenter')),
    url(r'^search/', include('search.urls',namespace = 'search')),
    url(r'^participate/', include('participate.urls',namespace = 'participate')),
    url(r'^readerService/', include('readerService.urls',namespace = 'readerService')),
    url(r'^librarian/', include('librarian.urls',namespace='librarian')),
    url(r'^ueditor/', include('DjangoUeditor.urls')),
    url(r'^infoCenter/', include('infoCenter.urls',namespace='infoCenter')),
    url(r'^service/', include('service.urls')),
    #张丽：登录图形验证码
    url(r'^captcha', include('captcha.urls')),
    url(r'media/(?P<path>.*)', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^upload/', include('upload.urls',namespace = 'upload')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DigitalLibrary/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

DigitalLibrary/infoCenter/urls.py
from django.conf.urls import url, include
from django.urls import path
from . import views

app_name = "infoCenter"

urlpatterns = [
    path('newsIntro/', views.newsIntro, name="newsIntro"), #新闻栏目简介
    path('newsColumn/<str:columnSlug>/', views.newsColumn, name="newsColumn"), #新闻列表
    path('newsDetail/', views.newsDetail, name="newsDetail"), #新闻文章详情

    path('recBookList/', views.recBookList, name="recBookList"), #每周一书列表
    path('recBookHis/', views.recBookDetail, name='recBookDetail'),

    path('rankList/', views.rankList, name="rankList"),  # 排行榜列表
    path('rankDetail/<int:rankID>/', views.rankDetail, name="rankDetail"), #排行榜详情

    path('toolDownload/', views.toolDownload, name="toolDownload"),  # 工具下载
    path('NoteExpress/', views.NoteExpress, name="NoteExpress"),  # NoteExpress下载
    path('EndNote/', views.EndNote, name="EndNote"),  # NoteExpress下载

    path('newsSearch/', views.newsSearch, name="newsSearch"),  # 新闻搜索结果

    path('recSource/', views.recSource, name="recSource"), #资源推送
]

DigitalLibrary/librarian/urls.py
from django.conf.urls import url

import librarian.views as views
app_name='librarian'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'index', views.index, name='index'),
    url(r'^librarian_book', views.librarian_book, name='librarian_book'),
    url(r'^librarian_Booktype', views.librarian_booktype, name='librarian_Booktype'),
    url(r'^librarian_borrow', views.librarian_borrow, name='librarian_borrow'),
    url(r'^librarian_history', views.librarian_reser, name='librarian_history'),
    url(r'^librarian_user', views.librarian_user,name='librarian_user'),
    url(r'^librarian_Usertype', views.librarian_usertype, name='librarian_Usertype'),
    url(r'^librarian_ebook', views.librarian_ebook, name='librarian_ebook'),
    url(r'^bookshelf', views.bookshelf, name='bookshelf'),
    url(r'^librarian_CD', views.librarian_CD, name='librarian_CD'),
    url(r'^add_user_to_database', views.add_user_to_database, name='add_user_to_database'),
    url(r'^add_book_to_database', views.add_book_to_database, name='add_book_to_database'),
    url(r'^add_CD_to_database', views.add_CD_to_database, name='add_CD_to_database'),
    url(r'^add_usertype_to_database', views.add_usertype_to_database, name='add_usertype_to_database'),
    url(r'^add_booktype_to_database', views.add_booktype_to_database, name='add_booktype_to_database'),
    url(r'^add_ebook_to_database', views.add_ebook_to_database, name='add_ebook_to_database'),
    url(r'^add_bookshelf_to_database', views.add_bookshelf_to_database, name='add_bookshelf_to_database'),
    url(r'^change_user_to_database', views.change_user_to_database, name='change_user_to_database'),
    url(r'^change_book_to_database', views.change_book_to_database, name='change_book_to_database'),
    url(r'^change_CD_to_database', views.change_CD_to_database, name='change_CD_to_database'),
    url(r'^change_usertype_to_database', views.change_usertype_to_database, name='change_usertype_to_database'),
    url(r'^change_booktype_to_database', views.change_booktype_to_database, name='change_booktype_to_database'),
    url(r'^change_ebook_to_database', views.change_ebook_to_database, name='change_ebook_to_database'),
    url(r'^change_bookshelf_to_database', views.change_bookshelf_to_database, name='change_bookshelf_to_database'),
    url(r'^delete_user', views.delete_user, name='delete_user'),
    url(r'^delete_borrowing_to_database', views.delete_borrowing_to_database, name='delete_borrowing_to_database'),
    url(r'^delete_CD_to_database', views.delete_CD_to_database, name='delete_CD_to_database'),
    url(r'^delete_book_to_database', views.delete_book_to_database, name='delete_book_to_database'),
    url(r'^delete_Usertype_to_database', views.delete_usertype_to_database, name='delete_Usertype_to_database'),
    url(r'^delete_booktype_to_database', views.delete_booktype_to_database, name='delete_booktype_to_database'),
    url(r'^delete_ebook_to_database', views.delete_ebook_to_database, name='delete_ebook_to_database'),
    url(r'^delete_bookshelf_to_database', views.delete_bookshelf_to_database, name='delete_bookshelf_to_database'),

]

DigitalLibrary/login/urls.py
from django.conf.urls import url
from django.contrib.staticfiles import views as static_views
from django.conf.urls.static import static
from django.conf import settings
from . import views
from django.urls import path

app_name ='login'

urlpatterns = [
                  #读者登录
                  path('rlogin/', views.reader_login, name='readerLogin'),
                  #馆员登录
                  path('liblogin/', views.librarian_login, name='librarianLogin'),
                  #登出
                  path('logout/', views.user_logout, name='user_logout'),
                  #注册
                  path('register/', views.user_register, name='userRegister'),
                  #修改密码
                  path('set_password/', views.set_password, name='set_password'),
    
              ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DigitalLibrary/participate/urls.py
# 引入path
from django.urls import path

# 引入views.py
from . import views

# 正在部署的应用的名称
app_name = 'participate'

urlpatterns = [
    # path函数将url映射到视图
    # 文章列表
    path('articleList/', views.article_list, name='article_list'),

     # 文章详情
    path('articleDetail/<int:id>/', views.article_detail, name='article_detail'),

    # 写文章
    path('articleCreate/', views.article_create, name='article_create'),

    # 删除文章
    path('articleDelete/<int:id>/', views.article_delete, name='article_delete'),

    # 安全删除文章
    path(
        'article-safe-delete/<int:id>/', views.article_safe_delete, name='article_safe_delete'),

    # 更新文章
    path('articleUpdate/<int:id>/', views.article_update, name='article_update'),

    # 发表评论
    path('postComment/<int:article_id>/', views.post_comment, name='post_comment'),

    # 捐赠须知
    path('donationRules/', views.donation_rules, name='donation_rules'),
    # 捐赠处理
    path('donationTreatments/', views.donation_treatments, name='donation_treatments'),
    # 联系方式
    path('donationContact/', views.donation_contact, name='donation_contact'),

    # 图书推荐
    path('bookRecom/', views.reader_recom, name='book_recommendation'),

    # 读者推荐列表
    path('bookRecList/', views.recom_list, name='bookrec_list'),

    # 推荐书目
    path('groupBook/', views.group_book, name='groupbook_recom'),
    #馆长信箱
    path('curatorMail/', views.curatorMail, name='curatorMail'),
    #论坛帮助
    path('listHelp/', views.listHelp, name='listHelp'),
    #联系我们
    path('contactus/', views.contactus, name='contactus'),
    #下载文件
    path('download_files/', views.download_files, name='download_files'),
    #论坛操作指南
    path('listTip/', views.listTip, name='listTip'),
    #论坛操作指南
    path('columnTag/', views.columnTag, name='columnTag'),
    #论坛操作指南
    path('map/', views.map, name='map'),
]

DigitalLibrary/readerService/urls.py
from django.urls import path,include
from readerService import views
app_name='readerService'

app_name = 'readerService'

urlpatterns = [
    path('bookReservation/',views.bookReservation, name='bookReservation'),
    path('bookReservationTips/',views.bookReservationTips, name='bookReservationTips'),
    path('bookReservationBooked/',views.bookReservationBooked, name='bookReservationBooked'),
    path('borrowTips/',views.borrowTips, name='borrowTips'),
    path('compensation/',views.compensation, name='compensation'),
    path('cd/',views.cd, name='cd'),
    path('cableNumber/', views.cableNumber, name='cableNumber'),
    path('cdInfo/', views.cdInfo, name='cdInfo'),
    path('renewal/', views.renewal, name='renewal'),
    path('serviceTime/', views.serviceTime, name='serviceTime'),
    path('lecture/', views.lecture, name='lecture'),
    path('lectureBook/', views.lectureBook, name='lectureBook'),
    path('lectureTips/', views.lectureTips, name='lectureTips'),
    path('bookReser$',views.bookReservationBooked)
]

DigitalLibrary/service/urls.py
from django.conf.urls import url, include
from django.urls import path
from . import views

app_name = 'service'

urlpatterns = [
    path('category/',views.libBrief, name = 'libBrief'),
    path('category/<str:categorySlug>/',views.serviceCategory, name='serviceCategory'),
    path('intro/', views.serviceDetail, name='serviceDetail'),
    path('serviceSearch/', views.serviceSearch, name="serviceSearch"),
]

DigitalLibrary/readerService/readerService/views.py
from django.shortcuts import render

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


from .models import bookReser
from .models import RedSerTime
from .models import lectureReser
from .models import CD

def bookReservation(request):
    if request.method=='GET':
        return render (request,'readerService/bookReservation.html')
    elif request.method=='POST':
        bookreser =bookReser()
        bookreser.readerId = request.POST.get('readerId')
        bookreser.book=request.POST.get('book')
        bookreser.bookId = request.POST.get('bookId')
        bookreser.returnTime = request.POST.get('returnTime')
        bookreser.place = request.POST.get('place')
        bookreser.save()
        return render (request,'readerService/success.html')

def bookReservationTips(request):
    bookreservationtips = RedSerTime.objects.all()
    return render(request, 'readerService/bookReservationTips.html', { 'bookreservationtips': bookreservationtips  })

def bookReservationBooked(request):
    bookResers = bookReser.objects.all()
    return render (request,'readerService/bookReservationBooked.html',{'bookResers':bookResers})

def borrowTips(request):
    borrowtips = RedSerTime.objects.all()
    return render(request, 'readerService/borrowTips.html', { 'borrowtips': borrowtips  })

def compensation(request):
    compensations = RedSerTime.objects.all()
    return render(request, 'readerService/compensation.html', { 'compensations': compensations  })

def cdInfo(request):
    cdinfos = RedSerTime.objects.all()
    return render(request, 'readerService/cdInfo.html', { 'cdinfos': cdinfos  })

def renewal(request):
    renewals = RedSerTime.objects.all()
    return render(request, 'readerService/renewal.html', { 'renewals': renewals  })

def cableNumber(request):
    cablenumbers = RedSerTime.objects.all()
    return render(request, 'readerService/cableNumber.html', { 'cablenumbers': cablenumbers  })


def cd(request):
    # 实现搜索
    q = request.GET.get('q')
    all_cds = CD.objects.all()
    cdlist = []
    # 如果前端传入关键字，才会进行检索，否则显示全部买家
    if q:
        for cd in all_cds:
            if q in cd.title:
                cdlist.append(cd)
        all_cds = cdlist
    if all_cds:
        paginator = Paginator(all_cds, 10)
        page = request.GET.get('page')
        try:
            contacts = paginator.page(page)
        except PageNotAnInteger:
            contacts = paginator.page(1)
        except EmptyPage:
            contacts = paginator.page(paginator.num_pages)
        context = {
            'contacts':contacts,
        }
        return render(request, 'readerService/cd.html', context)
    else:
        info = '暂无数据'
        return render(request, 'readerService/cd.html', {'info': info})

'''
def cd(request):
        # 实现搜索
        q = request.GET.get('q')
        all_cds = CD.objects.all()
        cdlist = []
        # 如果前端传入关键字，才会进行检索，否则显示全部买家
        if q:
            for cd in all_cds:
                if q in cd.title:
                    cdlist.append(cd)
            all_cds = cdlist
            return render(request, 'readerService/cd.html', {'all_cds':all_cds})

        current_path = request.get_full_path()

        # 翻页功能实现
        paginator = Paginator(all_cds, 5)
        pindex = request.GET.get('page', 1)

        try:
            # page是paginator实例对象的方法，返回第page页的实例对象，所以books是第page页的记录集
            pbooks = paginator.page(pindex)
        except PageNotAnInteger:
            pbooks = paginator.page(1)
        except EmptyPage:
            pbooks = paginator.page(paginator.num_pages)

        # ugly solution for &page=2&page=3&page=4
        # 当你已经是某一页时，current_path的最后有&page(previous),所以这里是在做清洗
        if '?page' in current_path:
            current_path = current_path.split('?page')[0]

        context = {
            'pbooks': pbooks,
            'current_path': current_path,
        }
        return render(request, 'readerService/cd.html', context)
'''

def serviceTime(request):
    servicetimes = RedSerTime.objects.all()
    return render(request, 'readerService/serviceTime.html', { 'servicetimes': servicetimes  })

def lecture(request):
    return render(request, 'readerService/lecture.html')

def lectureBook(request):
    if request.method=='GET':
        return render (request,'readerService/lectureBook.html')
    elif request.method=='POST':
        lecturereser =lectureReser()
        lecturereser.readerId = request.POST.get('readerId')
        lecturereser.email=request.POST.get('email')
        lecturereser.lectureName = request.POST.get('lectureName')
        lecturereser.speaker = request.POST.get('speaker')
        lecturereser.lectureTime = request.POST.get('lectureTime')
        lecturereser.save()
        return render (request,'readerService/success.html')

def lectureTips(request):
    return render(request, 'readerService/lectureTips.html')

DigitalLibrary/readerService/templates/header.html
<!DOCTYPE html>
<html lang="en">
 {% load static %}
 {% load staticfiles %}
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>数字图书馆首页</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- styles -->
  <!--搜索框选项要能显示正常需要-->
  <!--<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}"/> -->

  <!--搜索框样式结束-->
  <link href="{%static 'assets/css/bootstrap.css'%}" rel="stylesheet">
  <link href="{%static 'assets/css/bootstrap-responsive.css'%}" rel="stylesheet">
  <link href="{%static 'assets/css/docs.css'%}" rel="stylesheet">
  <link href="{%static 'assets/css/prettyPhoto.css'%}" rel="stylesheet">
  <link href="{%static 'assets/js/google-code-prettify/prettify.css'%}" rel="stylesheet">
  <link href="{%static 'assets/css/camera.css'%}" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,300|Open+Sans:400,300,300italic,400italic" rel="stylesheet">
  <link href="{%static 'assets/css/style.css'%}" rel="stylesheet">
  <link href="{%static 'assets/color/success.css'%}" rel="stylesheet">

  <!-- fav and touch icons -->
  <link rel="shortcut icon" href="{%static 'assets/ico/favicon.ico">
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{%static 'assets/ico/apple-touch-icon-144-precomposed.png'%}">
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{%static 'assets/ico/apple-touch-icon-114-precomposed.png'%}">
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{%static 'assets/ico/apple-touch-icon-72-precomposed.png'%}">
  <link rel="apple-touch-icon-precomposed" href="{%static 'assets/ico/apple-touch-icon-57-precomposed.png'%}">
  <link rel="stylesheet" href="/baidu/css/bootstrap.min.css"type="text/css"/>

  <!-- =======================================================
    Theme Name: Scaffold
    Theme URL: https://bootstrapmade.com/scaffold-bootstrap-metro-style-template/
    Author: BootstrapMade.com
    Author URL: https://bootstrapmade.com
  ======================================================= -->
</head>

<body>

  <header>
    <!-- Navbar
    ================================================== -->
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <!-- logo 数字图书馆 注意：需要制作一个大小一致的徽标 -->
          <a class="brand logo" href="index.html">
            <img src="{%static 'assets/img/sculogo1.png'%}" alt="scuIS" />
          </a>
          <!-- end logo -->

          <!-- top menu -->
          <div>
            <nav>
              <ul class="nav topnav">

                <li class="dropdown  active primary">
                  <a href="/"><i class="icon-home icon-white"></i>首页</a>
                  <!--<ul class="dropdown-menu">
                    <li><a href="index_alt1.html">Index alt 1</a></li>
                    <li><a href="index_alt2.html">Index alt 2</a></li>
                  </ul>  -->
                </li>

                <li class="dropdown warning">
                  <a href="{%url 'readerService:borrowTips'%}"><i class="icon-star icon-white"></i>读者服务</a>
                  <ul class="dropdown-menu">
                    <li><a href="{%url 'readerService:borrowTips'%}">借还图书</a></li>
                    <li><a href="{%url 'readerService:serviceTime'%}">服务时间</a></li>
                    <li><a href="{%url 'readerService:renewal'%}">续借与到期提醒</a></li>
                    <li><a href="{%url 'readerService:cableNumber'%}">索取号</a></li>
                    <li><a href="{%url 'readerService:compensation'%}">赔偿损失</a></li>
                    <li class="dropdown"><a href="{%url 'readerService:bookReservation'%}">图书预约</a>
                      <ul class="dropdown-menu sub-menu">
                        <li><a href="{%url 'readerService:bookReservationTips'%}">图书预约说明</a></li>
                        <li><a href="{%url 'readerService:bookReservationBooked'%}">已预约图书</a></li>
                        <li><a href="{%url 'readerService:bookReservation'%}">预约图书</a></li>
                      </ul>
                    </li>
                    <li class="dropdown "><a href="{%url 'readerService:cd'%}">随书光盘</a>
                      <ul class="dropdown-menu sub-menu">
                        <li><a href="{%url 'readerService:cd'%}">随书光盘检索</a></li>
                        <li><a href="{%url 'readerService:cdInfo'%}">随书光盘说明</a></li>
                      </ul>
                    </li>
                    <li class="dropdown "><a href="{%url 'readerService:lecture'%}">专题讲座</a>
                      <ul class="dropdown-menu sub-menu">
                        <li><a href="{%url 'readerService:lecture'%}">专题讲座</a></li>
                        <li><a href="{%url 'readerService:lectureBook'%}">讲座预约</a></li>
                        <li><a href="{%url 'readerService:lectureTips'%}">讲座预约须知</a></li>
                      </ul>
                    </li>
                  </ul>
                </li>

                <li class="dropdown danger">
                  <a href="{%url 'participate:article_list'%}"><i class="icon-leaf icon-white"></i>读者参与</a>
                  <ul class="dropdown-menu">
                    <li><a href="{%url 'participate:article_list'%}">读者论坛</a>
                        <ul class="dropdown-menu sub-menu">
                        <li><a href="{%url 'participate:article_list'%}">看帖</a></li>
                        <li><a href="{%url 'participate:article_create'%}">发帖</a></li>
                        <li><a href="{%url 'participate:listHelp'%}">论坛帮助</a></li>
                        </ul>
                    </li>
                    <li class="{%url 'participate:donation_rules'%}"><a href="#">图书捐赠</a>
                      <ul class="dropdown-menu sub-menu">
                        <li><a href="{%url 'participate:donation_rules'%}">捐赠须知</a></li>
                        <li><a href="{%url 'participate:donation_treatments'%}">捐赠处理</a></li>
                          <li><a href="{%url 'participate:donation_contact'%}">联系方式</a></li>
                      </ul>
                    </li>
                    <li class="dropdown"><a href="{%url 'participate:book_recommendation'%}">读者推荐</a>
                      <ul class="dropdown-menu sub-menu">
                        <li><a href="{%url 'participate:book_recommendation'%}">好书推荐</a></li>
                        <li><a href="{%url 'participate:bookrec_list'%}">推荐列表</a></li>
                      </ul>
                    </li>
                    <li><a href="{%url 'participate:groupbook_recom'%}">推荐书目</a></li>
                    <li><a href="{%url 'participate:curatorMail'%}">馆长信箱</a></li>
                  </ul>
                </li>
                <li class="dropdown info">
                    <a href="{% url 'infoCenter:newsIntro' %}"><i class="icon-camera icon-white"></i>信息中心</a>
                    <ul class="dropdown-menu">
                     <li class="dropdown "><a href="{% url 'infoCenter:newsIntro' %}">新闻公告</a>
                        <ul class="dropdown-menu sub-menu">
                          {% for column in news_intro_columns %}
                          <li><a href="{% url 'infoCenter:newsColumn' column.columnSlug %}">{{ column.columnName }}</a></li>
                          {% endfor %}
                        </ul>
                      </li>
                      <li class="dropdown"><a href="{% url 'service:libBrief' %}">服务指南</a>
                        <ul class="dropdown-menu sub-menu">
                          {% for category in side_cotegories %}
                          <li><a href="{% url 'service:serviceCategory' category.categorySlug %}">{{ category.categoryName }}</a></li>
                          {% endfor %}
                        </ul>
                      </li>
                      <li><a href="{% url 'infoCenter:recBookList' %}">每周一书</a></li>
                      <li><a href="{% url 'infoCenter:rankList' %}">排行榜</a></li>
                      <li><a href="{% url 'infoCenter:toolDownload' %}">工具下载</a></li>
                    </ul>
                </li>

                <li class="success">
                  <a href="{%url 'librarian:librarian_book' %}"><i class="icon-envelope icon-white"></i> 馆员管理</a>
                </li>
              {% if user.is_authenticated %}
                <li class="dropdown inverse">
                  <a href="{%url 'readerCenter:profile'%}"><i class="icon-bullhorn icon-white"></i>个人中心</a>
                  <ul class="dropdown-menu">
                    <li><a href="{%url 'readerCenter:profile'%}">个人资料</a></li>
                    <li><a href="{%url 'readerCenter:notice'%}">消息列表</a></li>
                    <li><a href="{%url 'readerCenter:borrowingSituation'%}">我的借阅</a></li>
                    <li><a href="{%url 'readerCenter:showsearchlist'%}">我的检索历史</a></li>
                    <li><a href="{%url 'readerCenter:mylib'%}">我的图书馆</a></li>
                    <li><a href="{%url 'login:user_logout'%}">登出</a></li>
                  </ul>
                </li>
              {%else%}
                <li class="dropdown inverse">
                  <a href="#"><i class="icon-bullhorn icon-white"></i> 登录/注册</a>
                  <ul class="dropdown-menu sub-menu">
                        <li><a href="{%url 'login:userRegister'%}">读者注册</a></li>
                        <li><a href="{%url 'login:readerLogin'%}">读者登录</a></li>
                        <li><a href="{%url 'login:librarianLogin'%}">馆员登录</a></li>
                        <li><a href="/admin/login/?next=/admin/">后台登录</a></li>
                  </ul>

                </li>
              {%endif%}
              </ul>
            </nav>
          </div>
          <!-- end menu -->
        </div>
      </div>
    </div>
  </header>
{% block content %}{% endblock %}

  <script src="{%static 'assets/js/jquery-1.8.2.min.js'%}"></script>
  <script src="{%static 'assets/js/jquery.easing.1.3.js'%}"></script>
  <script src="{%static 'assets/js/google-code-prettify/prettify.js'%}"></script>
  <script src="{%static 'assets/js/modernizr.js'%}"></script>
  <script src="{%static 'assets/js/bootstrap.js'%}"></script>
  <script src="{%static 'assets/js/jquery.elastislide.js'%}"></script>
  <script src="{%static 'assets/js/jquery.flexslider.js'%}"></script>
  <script src="{%static 'assets/js/jquery.prettyPhoto.js'%}"></script>
  <script src="{%static 'assets/js/application.js'%}"></script>
  <script src="{%static 'assets/js/hover/jquery-hover-effect.js'%}"></script>
  <script src="{%static 'assets/js/hover/setting.js'%}"></script>
  <script src="{%static 'assets/js/camera/camera.min.js'%}"></script>
  <script src="{%static 'assets/js/camera/setting.js'%}"></script>

  <!-- Template Custom JavaScript File -->
  <script src="{%static 'assets/js/custom.js'%}"></script>





</body>

</html>