DigitalLibrary/DigitalLibrary/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

#import login.views as login_view
import readerCenter.views as readerCenter_view
import search.views as search_view
import participate.views as participate_view
import readerService.views as readerService_view
import librarian.views as librarian_view
import service.views as service_view
import infoCenter.views as infoCenter_view
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve


urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^$', search_view.test, name='indextest'),
    url(r'^login/', include('login.urls',namespace = 'login')),
    url(r'^readerCenter/', include('readerCenter.urls',namespace = 'readerCenter')),
    url(r'^search/', include('search.urls',namespace = 'search')),
    url(r'^participate/', include('participate.urls',namespace = 'participate')),
    url(r'^readerService/', include('readerService.urls',namespace = 'readerService')),
    url(r'^librarian/', include('librarian.urls',namespace='librarian')),
    url(r'^ueditor/', include('DjangoUeditor.urls')),
    url(r'^infoCenter/', include('infoCenter.urls',namespace='infoCenter')),
    url(r'^service/', include('service.urls')),
    #张丽：登录图形验证码
    url(r'^captcha', include('captcha.urls')),
    url(r'media/(?P<path>.*)', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^upload/', include('upload.urls',namespace = 'upload')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DigitalLibrary/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

DigitalLibrary/infoCenter/urls.py
from django.conf.urls import url, include
from django.urls import path
from . import views

app_name = "infoCenter"

urlpatterns = [
    path('newsIntro/', views.newsIntro, name="newsIntro"), #新闻栏目简介
    path('newsColumn/<str:columnSlug>/', views.newsColumn, name="newsColumn"), #新闻列表
    path('newsDetail/', views.newsDetail, name="newsDetail"), #新闻文章详情

    path('recBookList/', views.recBookList, name="recBookList"), #每周一书列表
    path('recBookHis/', views.recBookDetail, name='recBookDetail'),

    path('rankList/', views.rankList, name="rankList"),  # 排行榜列表
    path('rankDetail/<int:rankID>/', views.rankDetail, name="rankDetail"), #排行榜详情

    path('toolDownload/', views.toolDownload, name="toolDownload"),  # 工具下载
    path('NoteExpress/', views.NoteExpress, name="NoteExpress"),  # NoteExpress下载
    path('EndNote/', views.EndNote, name="EndNote"),  # NoteExpress下载

    path('newsSearch/', views.newsSearch, name="newsSearch"),  # 新闻搜索结果

    path('recSource/', views.recSource, name="recSource"), #资源推送
]

DigitalLibrary/login/urls.py
from django.conf.urls import url
from django.contrib.staticfiles import views as static_views
from django.conf.urls.static import static
from django.conf import settings
from . import views
from django.urls import path

app_name ='login'

urlpatterns = [
                  #读者登录
                  path('rlogin/', views.reader_login, name='readerLogin'),
                  #馆员登录
                  path('liblogin/', views.librarian_login, name='librarianLogin'),
                  #登出
                  path('logout/', views.user_logout, name='user_logout'),
                  #注册
                  path('register/', views.user_register, name='userRegister'),
                  #修改密码
                  path('set_password/', views.set_password, name='set_password'),
    
              ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DigitalLibrary/participate/urls.py
# 引入path
from django.urls import path

# 引入views.py
from . import views

# 正在部署的应用的名称
app_name = 'participate'

urlpatterns = [
    # path函数将url映射到视图
    # 文章列表
    path('articleList/', views.article_list, name='article_list'),

     # 文章详情
    path('articleDetail/<int:id>/', views.article_detail, name='article_detail'),

    # 写文章
    path('articleCreate/', views.article_create, name='article_create'),

    # 删除文章
    path('articleDelete/<int:id>/', views.article_delete, name='article_delete'),

    # 安全删除文章
    path(
        'article-safe-delete/<int:id>/', views.article_safe_delete, name='article_safe_delete'),

    # 更新文章
    path('articleUpdate/<int:id>/', views.article_update, name='article_update'),

    # 发表评论
    path('postComment/<int:article_id>/', views.post_comment, name='post_comment'),

    # 捐赠须知
    path('donationRules/', views.donation_rules, name='donation_rules'),
    # 捐赠处理
    path('donationTreatments/', views.donation_treatments, name='donation_treatments'),
    # 联系方式
    path('donationContact/', views.donation_contact, name='donation_contact'),

    # 图书推荐
    path('bookRecom/', views.reader_recom, name='book_recommendation'),

    # 读者推荐列表
    path('bookRecList/', views.recom_list, name='bookrec_list'),

    # 推荐书目
    path('groupBook/', views.group_book, name='groupbook_recom'),
    #馆长信箱
    path('curatorMail/', views.curatorMail, name='curatorMail'),
    #论坛帮助
    path('listHelp/', views.listHelp, name='listHelp'),
    #联系我们
    path('contactus/', views.contactus, name='contactus'),
    #下载文件
    path('download_files/', views.download_files, name='download_files'),
    #论坛操作指南
    path('listTip/', views.listTip, name='listTip'),
    #论坛操作指南
    path('columnTag/', views.columnTag, name='columnTag'),
    #论坛操作指南
    path('map/', views.map, name='map'),
]

DigitalLibrary/readerCenter/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path
from . import views

app_name='readerCenter'

urlpatterns = [
                #个人资料
                path('profile/', views.profile, name='profile'),
                #更改个人资料
                path('changeinfo/', views.readerChangeinfo, name='changeinfo'),
                path('uploadImg/', views.uploadImg, name='uploadImg'),
                #消息列表
                path('notice/', views.readerNotice, name='notice'),
                #消息详情
                path('shownotice/', views.showNotice, name='noticeDetail'),
                #我的借阅
                path('bowrrowing/', views.readerBorrowing, name='borrowingSituation'),
                path('borrowHis/', views.readerBorrowHis, name='borrowHis'),
                path('moneyTask/', views.readerMoneyTask, name='moneyTask'),
                #我的借阅页面读者的借还操作
                url(r'^operatebook/', views.readerOperateBook, name='reader_operation'),
                #我的检索历史
                path('searchlist/', views.mysearchhis_show, name='showsearchlist'),
                path('searchlist_add/<str:ISBN>/', views.mysearchhis_add, name='mysearchhis_add'),
                path('searchlist_multi_add/', views.mysearchhis_multiadd, name='mysearchhis_multi_add'),
                path('searchlist_del/<str:id>/', views.mysearchhis_del, name='mysearchhis_del'),
                path('searchlist_multi_del/', views.mysearchhis_multidel, name='mysearchhis_multi_del'),
                #我的图书馆
                path('mylib/', views.mylib, name='mylib'),
                path('mylib_del/<str:ISBN>/', views.mylib_del, name='mylib_del'),
                path('mylib_add/<str:ISBN>/', views.mylib_add, name='mylib_add'),
                path('mylib_multi_add/', views.mylib_multiadd, name='mylib_multi_add'),
                path('mylib_search/', views.mylib_search, name='mylib_search'),
                #用户常用快速链接入口
                path('quickLink/', views.quickLink, name='quickLink'),
                #用户对搜索系统提出的建议
                path('searchAdvice/', views.adviceSearch, name='searchAdvice'),

    
              ]

DigitalLibrary/readerService/urls.py
from django.urls import path,include
from readerService import views
app_name='readerService'

app_name = 'readerService'

urlpatterns = [
    path('bookReservation/',views.bookReservation, name='bookReservation'),
    path('bookReservationTips/',views.bookReservationTips, name='bookReservationTips'),
    path('bookReservationBooked/',views.bookReservationBooked, name='bookReservationBooked'),
    path('borrowTips/',views.borrowTips, name='borrowTips'),
    path('compensation/',views.compensation, name='compensation'),
    path('cd/',views.cd, name='cd'),
    path('cableNumber/', views.cableNumber, name='cableNumber'),
    path('cdInfo/', views.cdInfo, name='cdInfo'),
    path('renewal/', views.renewal, name='renewal'),
    path('serviceTime/', views.serviceTime, name='serviceTime'),
    path('lecture/', views.lecture, name='lecture'),
    path('lectureBook/', views.lectureBook, name='lectureBook'),
    path('lectureTips/', views.lectureTips, name='lectureTips'),
    path('bookReser$',views.bookReservationBooked)
]

DigitalLibrary/search/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path,re_path
from . import views

app_name='search'

urlpatterns = [
                #检索首页
                path('searchindex/', views.index, name='searchindex'),
                #检索结果页
                path('searchBook/', views.book_search, name='searchBook'),
                #图书详情
                path('bookDetail/<str:ISBN>/', views.book_detail, name='bookDetail'),
                #参数设置
                path('searchParameter/', views.searchparameter, name='searchParameter'),
                #高级检索-多字段检索
                path('searchHigh/', views.search_multikeyword, name='searchHigh'),
                #高级检索-多字段检索结果
                path('searchHighResult/', views.multisearchlist, name='searchHighResult'),
                #检索帮助
                path('searchHelp/', views.search_help, name='searchHelp'),
                # 特殊格式
                path('bookDetailFormat/<str:ISBN>', views.bookDetail_format, name='bookDetailFormat'),
                path('bookDetailFormat_card/<str:ISBN>', views.bookDetail_format_card, name='bookDetailFormat_card'),
                path('bookDetailFormat_yinyong/<str:ISBN>', views.bookDetail_format_yinyong, name='bookDetailFormat_yinyong'),

              ]

DigitalLibrary/search/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django import forms
from .models import *

class SearchForm(forms.Form):
        CHOICES = [
            (u'模糊检索', u'模糊检索'),
            (u'ISBN', u'ISBN'),
            (u'书名', u'书名'),
            (u'作者', u'作者'),
            (u'图书目录', u'图书目录')
        ]

        search_by = forms.CharField(max_length=10,widget=forms.widgets.Select(choices=CHOICES))

        keyword = forms.CharField(
            label='',
            max_length=32,
            widget=forms.TextInput(attrs={
                'class': 'form-control input-lg',
                'placeholder': u'请输入图书信息，如书名、作者、分类......',
                'name': 'keyword',
            })
        )


class searchParameterForm(forms.Form):
    libCHOICES = [
        (u'豆瓣图书库', u'豆瓣图书库'),
        (u'四川大学图书馆书库', u'四川大学图书馆书库'),
        (u'全部数据库', u'全部数据库'),
    ]
    Format = [
        (u'非规范数据格式', u'非规范数据格式'),
        (u'标准格式', u'标准格式'),
        (u'卡片格式', u'卡片格式'),
        (u'引文格式', u'引文格式'),
    ]
    recordNumCHOICES = [
        (u'5', u'5'),
        (u'8', u'8'),
        (u'10', u'10'),
        (u'15', u'15'),
    ]
    crecordNumCHOICES = [
        (u'1', u'1'),
        (u'2', u'2'),
        (u'3', u'3'),
        (u'5', u'5'),
    ]

    recordNum=forms.IntegerField(
        max_value=20,
        min_value=5,
        label="每页显示记录数",
        widget=forms.NumberInput(

            attrs={
                'class': 'form-control input-lg',
                'name': 'recordNum',
            },

        ),
        required=False,
    )
    

    defaultLibrary = forms.CharField(
        max_length=20,
        label="默认检索分馆",
        widget=forms.widgets.Select(
            choices=libCHOICES,
            attrs={
                'class': 'form-control input-lg',
                'name': 'defaultLibrary',
            },
            
        ),
        required=False,)
    resultFormat = forms.CharField(
        max_length=20,
        label="默认规范数据格式",
        widget=forms.widgets.Select(
            choices=Format,
            attrs={
                'class': 'form-control input-lg',
                'name': 'resultFormat',
            },
        ),
        required=False,)


    


class multiKeywordsForm(forms.Form):
    book_lib_name = [ (u'豆瓣图书库', u'豆瓣图书库'),
        (u'四川大学图书馆书库', u'四川大学图书馆书库'),
        (u'全部数据库', u'全部数据库'),
                      ]

    catogary = forms.CharField(
        max_length=20,
        label="主题",
        widget=forms.TextInput(
            attrs={
                'class': 'form-control input-lg',
                'name': 'catogary',
            }
        ),
        required=False,

    )
    author = forms.CharField(
        max_length=20,
        label="著者",
        widget=forms.TextInput(
            attrs={

                'class': 'form-control input-lg',
                'name': 'author',
            }
        ),
        required=False,

    )
    title = forms.CharField(
        max_length=20,
        label="题名",
        widget=forms.TextInput(
            attrs={

                'class': 'form-control input-lg',
                'name': 'title',
            }
        ),
        required=False,

    )
    publishYear = forms.CharField(
        max_length=20,
        label="出版年",
        widget=forms.TextInput(
            attrs={

                'class': 'form-control input-lg',
                'name': 'publishYear',
            }
        ),
        required=False,

    )
    press = forms.CharField(
        max_length=20,
        label="出版社",
        widget=forms.TextInput(
            attrs={

                'class': 'form-control input-lg',
                'name': 'press',
            }
        ),
        required=False,

    )

    booklib = forms.CharField(
        max_length=20,
        label="书目库",
        widget=forms.Select(
            choices=book_lib_name,
            attrs={

                'class': 'form-control input-lg',
                'name': 'booklib',
            }
        ),
        required=False,

    )

DigitalLibrary/search/templates/search/book_detail.html
{% extends "login/base-1-testforlogin.html" %}
{% load staticfiles %}
{% block title %}查看图书{% endblock %}



{% block content %}
<style>
    button.btn.btn-primary.btn-lg {
    border-radius: 5px;
    width: auto;
    height: 35px;
}
</style>
    {%ifequal request.session.if_douban "yes"%}
        <div class="col-md-4 col-md-offset-4">
            <div class="alert alert-warning">
                <a href="/login" class="close" data-dismiss="alert">&times;</a>
                    <h2>豆瓣图书暂不支持规范格式，故展示非规范格式详情~</h2>
            </div>
        </div>
    {%endifequal%}

    {% if state %}
        <div class="col-md-4 col-md-offset-4">
            <div class="alert alert-warning">
                <a href="/login" class="close" data-dismiss="alert">&times;</a>
                {% if state == 'no_user' %}
                    <h2>请登陆</h2>
                {% elif state == 'upper_limit' %}
                    <h2> 对不起，您借书数量已经达到上线</h2>
                {% elif state == 'success' %}
                    <h2>借阅成功</h2>
                {% endif %}
            </div>
        </div>
    {% endif %}

    {% if book.quantity == 0 %}
        <div class="col-md-4 col-md-offset-4">
            <div class="alert alert-warning">
                <a href="/search/" class="close" data-dismiss="alert">&times;</a>
                    <h2> 对不起，此书已全部借出</h2>
            </div>
        </div>

    {% endif %}


    <div class="container myContainer">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="col-md-5">
                    <div class="img-rounded">
                      <img src="/media/bookcover/{{ book.cover }}" alt="{{ book.title }}">
                    </div>
                    <br><br><br>
                    <div class="col-md-2">
                        {% if book.bookID.quantity > 0 %}
                            <button class="btn btn-primary btn-lg"
                                    onclick="location.href='?action=borrow';">借阅
                            </button>
                        {% else %}
                            <button class="btn btn-primary btn-lg disabled">
                            借阅
                            </button>
                        {% endif %}

                    </div>
                    <div class="col-md-4">
                        <a href="{%url 'readerCenter:mylib_add' book.ISBN%}"> <button class="btn btn-primary btn-lg">添至我的图书馆</button> </a>
                    </div>
                   
                    <div class="col-md-5">
                        <a href="{%url 'search:bookDetailFormat' book.ISBN%}"> <button class="btn btn-primary btn-lg">图书信息规范数据格式</button> </a>
                    </div>
                </div>
                <div class="col-md-6 col-md-offset-1">
                    <h2 class="text-center">{{ book.title }}</h2>
                    <br>
                    <h4>ISBN：{{ book.ISBN }}</h4>
                    <h4>作者：{{ book.author }}</h4>
                    <h4>出版社:{{ book.press }}</h4>
                    <h4>类别：{{ book.category }}</h4>
                    <h4>价格：{{ book.price}}</h4>
                    <h4>位置:{{ book.bookID.location }}</h4>
                    <h4>在馆数量：{{ book.bookID.quantity }}</h4>
                    <hr>
                    <p>简介:</p>
                    <P>{{ book.description }}</p>
                    <hr>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

DigitalLibrary/search/templates/search/index.html
{% extends 'login/base.html' %}
{% load staticfiles %}
{% block title %} 欢迎来到图书馆！ {% endblock %}


{% block content %}
<style>
        #searchfather{
          
            display:flex;
            display: -webkit-flex;
        }
        
        #keyword{
            height: 50%;
            

        }
select#id_search_by {
    text-align: inherit;
    margin: 1px;
    font: inherit;
    color: #337ab7;
    padding: 12px 10px;
    border-radius: 5px;
}
 input#id_keyword {
    width: 350px;
    
}
    </style>


    <div class="container myContainer">

        <form action="{%url 'search:searchBook'%}" method="GET">
            <div class="row col-lg-7 col-lg-offset-3" id="searchfather">
                <div style="text-align:center; line-height:45px;"> <a href="{%url 'search:searchHigh'%}" >高级检索</a> </div>
                 <div class="input-group" id="searchby" >
                   {{ searchForm.search_by }}
                </div>
                <div class="input-group ">
                    {{ searchForm.keyword }}

                </div>
                <div class="input-group-btn" id="keyword">
                        <button class="btn btn-default btn-lg " type="submit"><img src="{%static 'login/img/search_gray.png'%}"></button>
                </div>
            </div>
        </form>
    </div>
    {% block searchResult %} {% endblock searchResult %}


{% endblock %}

DigitalLibrary/search/templates/search/index_test.html
{% extends 'login/base_test.html' %}
{% load static %}
{% load staticfiles %}
{% block content %}
<style>
  input#id_keyword {
    width: 400px;
    height: 80%;
    border-radius: 5px;
   
    border-weight:bold;
}
select#id_search_by {
    border-radius: 2px;
    width: 100px;
    height: 97%;
    
    border-weight:100px;
}
div#searchfather {
    display: flex;
    margin:2% 22%;
    
    

}
button.btn.btn-default.btn-lg {
    height: 100%;
    border-radius: 5px;
    
}

</style>
<!--轮换栏-->
  <section id="intro">
    <div class="jumbotron masthead">
      <div class="container">
        <div class="row">
          <div class="span12">
            <div class="camera_wrap camera_black_skin" id="camera_wrap_2">
              <!--点击轮换栏应进入对应的新闻界面 目前图片来源为四川省图书馆官网-->
              <div data-thumb="/media/backgrounds/searchindex_backgroud.jpg" data-src="/media/backgrounds/searchindex_backgroud.jpg">
                <div class="camera_caption fadeFromBottom">
                  <h2>图书馆重要宣传信息</h2>
                  <div class="hidden-phone">
                    <p>

                    </p>
                  </div>
                </div>
              </div>
              
              <div data-thumb="/media/backgrounds/searchindex_backgroud-1.jpg" data-src="/media/backgrounds/searchindex_backgroud-1.jpg">
                <div class="camera_caption fadeFromBottom">
                  <h2>成都市图书馆</h2>
                  <div class="hidden-phone">
                    <p>
                      <!--{{var}}图书推荐语-->
                    </p>
                  </div>
                </div>
              </div>

              <div data-thumb="/media/backgrounds/searchindex_backgroud-2.jpg" data-src="/media/backgrounds/searchindex_backgroud-2.jpg">
                <div class="camera_caption fadeFromBottom">
                  <h2>四川大学</h2>
                  <div class="hidden-phone">
                    <p>
                      <!--{{var}}图书推荐语-->
                    </p>
                  </div>
                </div>
              </div>

              <div data-thumb="/media/backgrounds/searchindex_backgroud-1.jpg" data-src="/media/backgrounds/searchindex_backgroud-1.jpg">
                <div class="camera_caption fadeFromBottom">
                  <h2>四川大学</h2>
                  <div class="hidden-phone">
                    <p>
                       <!--{{var}}图书推荐语-->
                    </p>
                  </div>
                </div>
              </div>
            </div>
            <!-- #camera_wrap_1 -->

          </div>
        </div>
      </div>
    </div>
  </section>


   <div class="container myContainer ">
        <form action="{%url 'search:searchBook'%}" method="GET">
            <div class="row col-lg-7 col-lg-offset-3" id="searchfather">
                <div style="text-align:center; line-height:45px;"> <a href="{%url 'search:searchHigh'%}" >高级检索</a> </div>
                 <div class="input-group" id="searchby" >
                   {{ searchForm.search_by }}
                </div>
                <div class="input-group ">
                    {{ searchForm.keyword }}

                </div>
                <div class="input-group-btn" id="keyword">
                        <button class="btn btn-default btn-lg " type="submit"><img src="{%static 'login/img/search_gray.png'%}"></button>
                </div>
            </div>
        </form>
    </div>  




  <section id="maincontent">
    <div class="container">

      <div class="row">

        <div class="span3">
          <h3 class="heading-success"><span class="btn btn-large btn-success"><i class="m-icon-big-swapright m-icon-white"></i></span>&nbsp;&nbsp;读者核心</h3>
          <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;本数字图书馆面向广大市民朋友们与图书馆工作人员，提供书籍检索、读者服务。点击尝试！</p>
        </div>

       <div class="span3">
           <a href="{%url 'search:searchindex'%}"><div class="well well-primary box">
            <img src="{%static 'assets/img/icons/box-1-white.png'%}" alt="" />
            <h3>图书检索</h3>
            <p>检索馆藏图书&检索电子图书</p>
          </div> </a>
        </div>

        <div class="span3">

           <a href="{%url 'readerService:borrowTips'%}"><div class="well well-success box">
            <img src="{%static 'assets/img/icons/box-2-white.png'%}" alt="" />
            <h3>借阅服务</h3>
            <p>借阅与预约图书说明 </p>

           </div></a>
          </div>

        <div class="span3">
          <a href="{% url 'participate:article_list' %}"><div class="well well-warning box">
            <img src="{%static 'assets/img/icons/box-3-white.png'%}" alt="" />
            <h3>在线论坛</h3>
            <p>
                提供交流、建议的平台
            </p>
          </div>
          </a></div>

      </div>
          


      </div>

  </section>

  <section id="maincontent">
    <div class="container">

      <div class="row">

        <div class="span3">
          <h3 class="heading-success"><a href="{% url 'infoCenter:newsIntro' %}"><span class="btn btn-large btn-success"><i class="m-icon-big-swapright m-icon-white"></i></span>&nbsp;&nbsp;新闻资讯</a></h3>
          <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;关注图书馆新闻资讯，了解图书上新、馆内活动等一切你想知道的信息！</p>
        </div>
        {%for newsColum in index_news_column %}
              <div class="span3">
                 <table class="table table-condensed">
                    <caption>{{newsColum.columnName}}</caption>
                    <thead>
                      <tr>
                        <th>标题</th>
                        <th>日期</th>
                        <th><a href="{% url 'infoCenter:newsColumn' newsColum.columnSlug %}">更多</a></th></tr>
                    </thead>
                    <tbody>
                      {% for item in index_news  %}
                        {% if item.newsColumn.pk == newsColum.pk %}
                          <tr>
                            <td><a onclick="location.href='/infoCenter/newsDetail/?pk={{item.pk}}&newsSlug={{item.newsSlug}}';">
                                {% if item.topDisplay %}
                                <b>【置顶】{{item.newsTitle}}</b>
                                {% else %}
                                {{item.newsTitle}}
                                {% endif %}
                            </a></td>
                            <td>{{item.newsPubdate}}</td></tr>
                        {% endif %}
                      {% endfor %}
                    </tbody>
                  </table>
              </div>
        {%endfor%}
      </div>

    </div>
  </section>


  <section id="bottom">
    <div class="container">

      <!-- divider -->
      <div class="row">
        <div class="span12">
          <div class="divider"></div>
        </div>
      </div>
      <!-- end divider -->

      <!--每周一书-往期书籍-->
      <div class="row">
        <div class="span12">
          <h3><a class="btn btn-large btn-success" href="{% url 'infoCenter:recBookList' %}"><i class="m-icon-big-swapdown m-icon-white"></i></a> 每周推荐</h3>
          <div id="latest-work" class="carousel btleft">
            <div class="carousel-wrapper">

              <ul class="portfolio-home da-thumbs">
                {% for book in recbooks %}
                <li>
                  <div class="thumbnail">
                    <div class="image-wrapp">
                      <img src="/media/bookcover/index_recbook.jpg" alt="{{ book.ISBN.title }}" title="" />
                      <article class="da-animate da-slideFromRight" style="display: block;">
                        <a class="link_post" onclick="location.href='/infoCenter/recBookHis/?pk={{book.pk}}&recID={{book.recID}}';">
                          <img src="{%static 'assets/img/icons/link_post_icon.png'%}" alt="" />
                        </a>
                        <span><a class="zoom" data-pretty="prettyPhoto" href="/media/bookcover/{{ book.ISBN.cover }}">
                          <img src="{%static 'assets/img/icons/zoom_icon.png'%}" alt="{{ book.ISBN.title }}" title="{{ book.ISBN.title }}" />
                        </a></span>
                      </article>
                    </div>
                    <div class="caption">
                      <h5>{{ book.bookName }}</h5>
                    </div>

                  </div>
                </li>
                {% endfor %}
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- Footer
 ================================================== -->
  <footer class="footer">
    <div class="container">
      <div class="row">

      </div>
    </div>  

    <div class="verybottom">
      <div class="container">
        <div class="row">
          <div class="span6">
            <p>&copy;五朵金花</p>
          </div>
          <div class="span6">
            <div class="pull-right">
              <div class="credits">
                <!--
                  All the links in the footer should remain intact.
                  You can delete the links only if you purchased the pro version.
                  Licensing information: https://bootstrapmade.com/license/
                  Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=Scaffold
                -->
                 <a href="{%url 'participate:map'%}">网站地图</a>
              </div>
            </div>
          </div>
        </div>
      </div>

    </div>
  </footer>

{% endblock %}