DigitalLibrary/DigitalLibrary/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

#import login.views as login_view
import readerCenter.views as readerCenter_view
import search.views as search_view
import participate.views as participate_view
import readerService.views as readerService_view
import librarian.views as librarian_view
import service.views as service_view
import infoCenter.views as infoCenter_view
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve


urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^$', search_view.test, name='indextest'),
    url(r'^login/', include('login.urls',namespace = 'login')),
    url(r'^readerCenter/', include('readerCenter.urls',namespace = 'readerCenter')),
    url(r'^search/', include('search.urls',namespace = 'search')),
    url(r'^participate/', include('participate.urls',namespace = 'participate')),
    url(r'^readerService/', include('readerService.urls',namespace = 'readerService')),
    url(r'^librarian/', include('librarian.urls',namespace='librarian')),
    url(r'^ueditor/', include('DjangoUeditor.urls')),
    url(r'^infoCenter/', include('infoCenter.urls',namespace='infoCenter')),
    url(r'^service/', include('service.urls')),
    #张丽：登录图形验证码
    url(r'^captcha', include('captcha.urls')),
    url(r'media/(?P<path>.*)', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^upload/', include('upload.urls',namespace = 'upload')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DigitalLibrary/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

DigitalLibrary/librarian/urls.py
from django.conf.urls import url

import librarian.views as views
app_name='librarian'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'index', views.index, name='index'),
    url(r'^librarian_book', views.librarian_book, name='librarian_book'),
    url(r'^librarian_Booktype', views.librarian_booktype, name='librarian_Booktype'),
    url(r'^librarian_borrow', views.librarian_borrow, name='librarian_borrow'),
    url(r'^librarian_history', views.librarian_reser, name='librarian_history'),
    url(r'^librarian_user', views.librarian_user,name='librarian_user'),
    url(r'^librarian_Usertype', views.librarian_usertype, name='librarian_Usertype'),
    url(r'^librarian_ebook', views.librarian_ebook, name='librarian_ebook'),
    url(r'^bookshelf', views.bookshelf, name='bookshelf'),
    url(r'^librarian_CD', views.librarian_CD, name='librarian_CD'),
    url(r'^add_user_to_database', views.add_user_to_database, name='add_user_to_database'),
    url(r'^add_book_to_database', views.add_book_to_database, name='add_book_to_database'),
    url(r'^add_CD_to_database', views.add_CD_to_database, name='add_CD_to_database'),
    url(r'^add_usertype_to_database', views.add_usertype_to_database, name='add_usertype_to_database'),
    url(r'^add_booktype_to_database', views.add_booktype_to_database, name='add_booktype_to_database'),
    url(r'^add_ebook_to_database', views.add_ebook_to_database, name='add_ebook_to_database'),
    url(r'^add_bookshelf_to_database', views.add_bookshelf_to_database, name='add_bookshelf_to_database'),
    url(r'^change_user_to_database', views.change_user_to_database, name='change_user_to_database'),
    url(r'^change_book_to_database', views.change_book_to_database, name='change_book_to_database'),
    url(r'^change_CD_to_database', views.change_CD_to_database, name='change_CD_to_database'),
    url(r'^change_usertype_to_database', views.change_usertype_to_database, name='change_usertype_to_database'),
    url(r'^change_booktype_to_database', views.change_booktype_to_database, name='change_booktype_to_database'),
    url(r'^change_ebook_to_database', views.change_ebook_to_database, name='change_ebook_to_database'),
    url(r'^change_bookshelf_to_database', views.change_bookshelf_to_database, name='change_bookshelf_to_database'),
    url(r'^delete_user', views.delete_user, name='delete_user'),
    url(r'^delete_borrowing_to_database', views.delete_borrowing_to_database, name='delete_borrowing_to_database'),
    url(r'^delete_CD_to_database', views.delete_CD_to_database, name='delete_CD_to_database'),
    url(r'^delete_book_to_database', views.delete_book_to_database, name='delete_book_to_database'),
    url(r'^delete_Usertype_to_database', views.delete_usertype_to_database, name='delete_Usertype_to_database'),
    url(r'^delete_booktype_to_database', views.delete_booktype_to_database, name='delete_booktype_to_database'),
    url(r'^delete_ebook_to_database', views.delete_ebook_to_database, name='delete_ebook_to_database'),
    url(r'^delete_bookshelf_to_database', views.delete_bookshelf_to_database, name='delete_bookshelf_to_database'),

]

DigitalLibrary/login/urls.py
from django.conf.urls import url
from django.contrib.staticfiles import views as static_views
from django.conf.urls.static import static
from django.conf import settings
from . import views
from django.urls import path

app_name ='login'

urlpatterns = [
                  #读者登录
                  path('rlogin/', views.reader_login, name='readerLogin'),
                  #馆员登录
                  path('liblogin/', views.librarian_login, name='librarianLogin'),
                  #登出
                  path('logout/', views.user_logout, name='user_logout'),
                  #注册
                  path('register/', views.user_register, name='userRegister'),
                  #修改密码
                  path('set_password/', views.set_password, name='set_password'),
    
              ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DigitalLibrary/readerCenter/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path
from . import views

app_name='readerCenter'

urlpatterns = [
                #个人资料
                path('profile/', views.profile, name='profile'),
                #更改个人资料
                path('changeinfo/', views.readerChangeinfo, name='changeinfo'),
                path('uploadImg/', views.uploadImg, name='uploadImg'),
                #消息列表
                path('notice/', views.readerNotice, name='notice'),
                #消息详情
                path('shownotice/', views.showNotice, name='noticeDetail'),
                #我的借阅
                path('bowrrowing/', views.readerBorrowing, name='borrowingSituation'),
                path('borrowHis/', views.readerBorrowHis, name='borrowHis'),
                path('moneyTask/', views.readerMoneyTask, name='moneyTask'),
                #我的借阅页面读者的借还操作
                url(r'^operatebook/', views.readerOperateBook, name='reader_operation'),
                #我的检索历史
                path('searchlist/', views.mysearchhis_show, name='showsearchlist'),
                path('searchlist_add/<str:ISBN>/', views.mysearchhis_add, name='mysearchhis_add'),
                path('searchlist_multi_add/', views.mysearchhis_multiadd, name='mysearchhis_multi_add'),
                path('searchlist_del/<str:id>/', views.mysearchhis_del, name='mysearchhis_del'),
                path('searchlist_multi_del/', views.mysearchhis_multidel, name='mysearchhis_multi_del'),
                #我的图书馆
                path('mylib/', views.mylib, name='mylib'),
                path('mylib_del/<str:ISBN>/', views.mylib_del, name='mylib_del'),
                path('mylib_add/<str:ISBN>/', views.mylib_add, name='mylib_add'),
                path('mylib_multi_add/', views.mylib_multiadd, name='mylib_multi_add'),
                path('mylib_search/', views.mylib_search, name='mylib_search'),
                #用户常用快速链接入口
                path('quickLink/', views.quickLink, name='quickLink'),
                #用户对搜索系统提出的建议
                path('searchAdvice/', views.adviceSearch, name='searchAdvice'),

    
              ]

DigitalLibrary/librarian/models.py
from django.db import models

# Create your models here.

from django.urls import reverse  # To generate URLS by reversing URL patterns

DigitalLibrary/librarian/forms.py
from django import forms
from login.models import Reader, readerType
from search.models import ebook_info ,bookEntity_info , bookshelf_info, booktype_info
from readerCenter.models import Borrowing
from readerService.models import CD,bookReser

'''class NewUserForm(forms.Form):
    gender = (
        ('male', "男"),
        ('female', "女"),
    )
    username = forms.CharField(label="用户名", max_length=128, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label="密码", max_length=256, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    readertypeName = forms.CharField(label="读者类型名称", max_length=30, widget=forms.TextInput(attrs={'class': 'form-control'}))
    bookNumber = forms.IntegerField(label="最大可借图书数", widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(label="邮箱地址", widget=forms.EmailInput(attrs={'class': 'form-control'}))
    sex = forms.ChoiceField(label='性别', choices=gender)


class ChangeUserForm(forms.Form):
    gender = (
        ('male', "男"),
        ('female', "女"),
    )
    oldusername = forms.CharField(label="原始用户名", max_length=128, widget=forms.TextInput(attrs={'class': 'form-control','id':'oldusername','placeholder':"请输入原来的用户名"}))
    username = forms.CharField(label="新的用户名", max_length=128, widget=forms.TextInput(attrs={'class': 'form-control','id':'updateusername','placeholder':"请输入新的用户名"}))
    password = forms.CharField(label="密码", max_length=256, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    readertypeName = forms.CharField(label="读者类型名称", max_length=30, widget=forms.TextInput(attrs={'class': 'form-control'}))
    bookNumber = forms.IntegerField(label="最大可借图书数", widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(label="邮箱地址", widget=forms.EmailInput(attrs={'class': 'form-control'}))
    sex = forms.ChoiceField(label='性别', choices=gender)'''

class ReaderForm(forms.ModelForm):
    class Meta:
        model = Reader
        fields = ['name','Password','balance','max_borrowing','Sex']

class AddReaderForm(forms.ModelForm):
    class Meta:
        model = Reader
        fields = ['name','Password','email','balance','max_borrowing','Sex']

class BookshelfForm(forms.ModelForm):
    class Meta:
        model = bookshelf_info
        fields = "__all__"
        exclude = ["bookshelfID"]

class BookForm(forms.ModelForm):
    class Meta:
        model = bookEntity_info
        fields = "__all__"


class EbookForm(forms.ModelForm):
    class Meta:
        model = ebook_info
        fields = "__all__"

class BookTypeForm(forms.ModelForm):
    class Meta:
        model = booktype_info
        fields = "__all__"
        exclude = ["btID"]

class ReaderTypeForm(forms.ModelForm):
    class Meta:
        model = readerType
        fields = "__all__"

class BorrowingForm(forms.ModelForm):
    class Meta:
        model = Borrowing
        fields = "__all__"


class CDForm(forms.ModelForm):
    class Meta:
        model = CD
        fields = "__all__"

class reserForm(forms.ModelForm):
    class Meta:
        model = bookReser
        fields = "__all__"

DigitalLibrary/librarian/templates/librarian/Addinfo.html
{% extends "librarian/pers_base_ver1.html" %}
{% load staticfiles %}
{% block title %}修改个人信息{% endblock %}

{%block perscontent%}
<style>
    select, textarea, input[type="text"], input[type="password"], input[type="datetime"], input[type="datetime-local"], input[type="date"], input[type="month"], input[type="time"], input[type="week"], input[type="number"], input[type="email"], input[type="url"], input[type="search"], input[type="tel"], input[type="color"], .uneditable-input {
    -webkit-border-radius: 0;
    -moz-border-radius: 0;
    border-radius: 5px;
    width: 221px;
    height:30px;
}
</style>
 <div id="content-wrapper">

      <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">

                {% if message %}
                    <div class="alert alert-success text-center">
                        <a href="#" class="close" data-dismiss="alert">&times;</a>
                        {% if message == 'success' %}
                            <h2><a href="{%url 'readerCenter:profile'%}">修改成功,点击返回个人中心页面</a></h2>
                        {% endif %}
                    </div>
                {% endif %}

                <div class="card mb-3">
                    <div class="card-header">
                    <i></i>
                    {{tishi}}</div>
                    <div class="card-body">
                        <form  role="form" class="form-horizontal" method="post" action="{{action}}">
                            {% csrf_token %}
                            <!--<h1 class="form-signin-heading text-center">修改个人信息</h1> -->

                            {% for field in userprofile_form %}
                                <div class="form-group">
                                    <label class="col-md-3 control-label">{{ field.label }}</label>
                                    <div class="col-md-9">
                                        {{ field }}
                                    </div>
                                </div>
                            {% endfor %}
                            <div class="form-group">
                                <div class="col-md-4 col-md-offset-4">
                                    <button class="btn btn btn-primary btn-block" type="submit">提交</button>
                                </div>
                            </div>
                        </form>

                    </div>

              </div>

            </div>

        </div>
    </div>
   </div>



{% endblock perscontent %}

DigitalLibrary/librarian/templates/librarian/booktypeChangeinfo.html
{% extends "librarian/pers_base_ver1.html" %}
{% load staticfiles %}
{% block title %}修改个人信息{% endblock %}

{%block perscontent%}
<style>
    select, textarea, input[type="text"], input[type="password"], input[type="datetime"], input[type="datetime-local"], input[type="date"], input[type="month"], input[type="time"], input[type="week"], input[type="number"], input[type="email"], input[type="url"], input[type="search"], input[type="tel"], input[type="color"], .uneditable-input {
    -webkit-border-radius: 0;
    -moz-border-radius: 0;
    border-radius: 5px;
    width: 221px;
    height:30px;
}
</style>
 <div id="content-wrapper">

      <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">

                {% if message %}
                    <div class="alert alert-success text-center">
                        <a href="#" class="close" data-dismiss="alert">&times;</a>
                        {% if message == 'success' %}
                            <h2><a href="{%url 'readerCenter:profile'%}">修改成功,点击返回个人中心页面</a></h2>
                        {% endif %}
                    </div>
                {% endif %}

                <div class="card mb-3">
                    <div class="card-header">
                    <i></i>
                    修改图书类型信息</div>
                    <div class="card-body">
                        <form  role="form" class="form-horizontal" method="post" action="change_booktype_to_database?id={{booktype.btID}}">
                            {% csrf_token %}
                            <!--<h1 class="form-signin-heading text-center">修改个人信息</h1> -->

                            {% for field in userprofile_form %}
                                <div class="form-group">
                                    <label class="col-md-3 control-label">{{ field.label }}</label>
                                    <div class="col-md-9">
                                        {{ field }}
                                    </div>
                                </div>
                            {% endfor %}
                            <div class="form-group">
                                <div class="col-md-4 col-md-offset-4">
                                    <button class="btn btn btn-primary btn-block" type="submit">提交</button>
                                </div>
                            </div>
                        </form>

                    </div>

              </div>

            </div>

        </div>
    </div>
   </div>



{% endblock perscontent %}

DigitalLibrary/librarian/templates/librarian/pers_base_ver1.html
{% extends "readerCenter/base_index_navtop.html" %}
{% load static %}
{% load staticfiles %}
{% block content %}
    <link href="{% static 'readerCenter/vendor/datatables/dataTables.bootstrap4.css'%}" rel="stylesheet">

      <!-- Custom styles for this template-->
      <link href="{%static 'css/sb-admin.css'%}" rel="stylesheet">
      <link href="readerCenter/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
      <!--custom css for perprofile-->
      <link href="{%static 'css/circular-images.css'%}" rel="stylesheet">

    <!--custom from base.html-->
     <link href="{% static 'readerCenter/vendor/fontawesome-free/css/all.css' %}" rel="stylesheet">
      <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
      <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <!--小梦的静态文件，用于显示侧边导航栏-->

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-admin-theme.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-admin-theme.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <script src="{% static 'js/bootstrap-dropdown.min.js' %}"></script>
    <script src="{% static 'ajax-lib/ajaxutils.js' %}"></script>
    <script src="{% static 'js/adminUpdateInfo.js' %}"></script>
    <script src="{% static 'js/adminUpdatePwd.js' %}"></script>


  <link href="{%static 'assets/css/bootstrap.css'%}" rel="stylesheet">
  <link href="{%static 'assets/css/bootstrap-responsive.css'%}" rel="stylesheet">
  <link href="{%static 'assets/css/docs.css'%}" rel="stylesheet">
  <link href="{%static 'assets/css/prettyPhoto.css'%}" rel="stylesheet">
  <link href="{%static 'assets/js/google-code-prettify/prettify.css'%}" rel="stylesheet">
  <link href="{%static 'assets/css/camera.css'%}" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,300|Open+Sans:400,300,300italic,400italic" rel="stylesheet">
  <link href="{%static 'assets/css/style.css'%}" rel="stylesheet">
  <link href="{%static 'assets/color/success.css'%}" rel="stylesheet">

  <!-- fav and touch icons -->
  <link rel="shortcut icon" href="{%static 'assets/ico/favicon.ico">
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{%static 'assets/ico/apple-touch-icon-144-precomposed.png'%}">
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{%static 'assets/ico/apple-touch-icon-114-precomposed.png'%}">
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{%static 'assets/ico/apple-touch-icon-72-precomposed.png'%}">
  <link rel="apple-touch-icon-precomposed" href="{%static 'assets/ico/apple-touch-icon-57-precomposed.png'%}">
  <link rel="stylesheet" href="/baidu/css/bootstrap.min.css"type="text/css"/>

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

<script src="{%static 'assets/js/jquery-1.8.2.min.js'%}"></script>
  <script src="{%static 'assets/js/jquery.easing.1.3.js'%}"></script>
  <script src="{%static 'assets/js/google-code-prettify/prettify.js'%}"></script>
  <script src="{%static 'assets/js/modernizr.js'%}"></script>
  <script src="{%static 'assets/js/bootstrap.js'%}"></script>
  <script src="{%static 'assets/js/jquery.elastislide.js'%}"></script>
  <script src="{%static 'assets/js/jquery.flexslider.js'%}"></script>
  <script src="{%static 'assets/js/jquery.prettyPhoto.js'%}"></script>
  <script src="{%static 'assets/js/application.js'%}"></script>
  <script src="{%static 'assets/js/hover/jquery-hover-effect.js'%}"></script>
  <script src="{%static 'assets/js/hover/setting.js'%}"></script>
  <script src="{%static 'assets/js/camera/camera.min.js'%}"></script>
  <script src="{%static 'assets/js/camera/setting.js'%}"></script>

  <!-- Template Custom JavaScript File -->
  <script src="{%static 'assets/js/custom.js'%}"></script>

<!--end for base.html-->
<div class="container" style="margin-top:18px"><!--张丽：页面整文距离顶栏的距离，相当重要，其他地方设置该样式会被覆盖-->
        <!-- left, vertical navbar & content -->
        <div class="row" >
            <!-- left, vertical navbar -->
             <div class="col-md-2 bootstrap-admin-col-left">
                <ul class="nav navbar-collapse collapse bootstrap-admin-navbar-side">
                    <li>
                        <a href="{%url 'librarian:librarian_book'%}"><i class="glyphicon glyphicon-chevron-right"></i> 图书管理</a>
                    </li>
                    <li>
                        <a href="{%url 'librarian:librarian_ebook'%}"><i class="glyphicon glyphicon-chevron-right"></i> 电子图书管理</a>
                    </li>
                    <li>
                        <a href="{%url 'librarian:bookshelf'%}"><i class="glyphicon glyphicon-chevron-right"></i> 书架管理</a>
                    </li>
                    <li>
                        <a href="{%url 'librarian:librarian_CD'%}"><i class="glyphicon glyphicon-chevron-right"></i> 光盘管理</a>
                    </li>
                    <li>
                        <a href="{%url 'librarian:librarian_user'%}"><i class="glyphicon glyphicon-chevron-right"></i> 读者管理</a>
                    </li>
                    <li>
                        <a href="{%url 'librarian:librarian_Usertype'%}"><i class="glyphicon glyphicon-chevron-right"></i> 读者类型管理</a>
                    </li>
                    <li>
                        <a href="{%url 'librarian:librarian_Booktype'%}"><i class="glyphicon glyphicon-chevron-right"></i> 图书分类管理</a>
                    </li>
                    <li>
                        <a href="{%url 'librarian:librarian_borrow'%}"><i class="glyphicon glyphicon-chevron-right"></i> 图书借阅信息</a>
                    </li>
                    <li>
                        <a href="{%url 'librarian:librarian_history'%}"><i class="glyphicon glyphicon-chevron-right"></i> 图书预约信息</a>
                    </li>

                </ul>

            </div>
            <div class="col-md-10">


                {%block perscontent%}

                {%endblock perscontent%}
    <!-- /.content-wrapper -->

            </div>
        </div>


    </div>
</div>


 <!-- Bootstrap core JavaScript-->
  <script src="{%static 'readerCenter/vendor/jquery/jquery.min.js'%}"></script>
  <script src="{%static 'readerCenter/vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{%static 'readerCenter/vendor/jquery-easing/jquery.easing.min.js'%}"></script>

  <!-- Page level plugin JavaScript-->
  <script src="{%static 'readerCenter/vendor/chart.js/Chart.js'%}"></script>
  <script src="{%static 'readerCenter/vendor/datatables/jquery.dataTables.js'%}"></script>
  <script src="{%static 'readerCenter/vendor/datatables/dataTables.bootstrap4.js'%}"></script>


  <!-- Demo scripts for this page-->
  <script src="{%static 'js/demo/datatables-demo.js'%}"></script>
  <script src="{%static 'js/demo/chart-area-demo.js'%}"></script>


<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
{% endblock %}

DigitalLibrary/librarian/templates/librarian/userChangeinfo.html
{% extends "librarian/pers_base_ver1.html" %}
{% load staticfiles %}
{% block title %}修改个人信息{% endblock %}

{%block perscontent%}
<style>
    select, textarea, input[type="text"], input[type="password"], input[type="datetime"], input[type="datetime-local"], input[type="date"], input[type="month"], input[type="time"], input[type="week"], input[type="number"], input[type="email"], input[type="url"], input[type="search"], input[type="tel"], input[type="color"], .uneditable-input {
    -webkit-border-radius: 0;
    -moz-border-radius: 0;
    border-radius: 5px;
    width: 221px;
    height:30px;
}
</style>
 <div id="content-wrapper">

      <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">

                {% if message %}
                    <div class="alert alert-success text-center">
                        <a href="#" class="close" data-dismiss="alert">&times;</a>
                        {% if message == 'success' %}
                            <h2><a href="{%url 'readerCenter:profile'%}">修改成功,点击返回个人中心页面</a></h2>
                        {% endif %}
                    </div>
                {% endif %}

                <div class="card mb-3">
                    <div class="card-header">
                    <i></i>
                    修改个人信息</div>
                    <div class="card-body">
                        <form  role="form" class="form-horizontal" method="post" action="change_user_to_database?email={{reader.email}}">
                            {% csrf_token %}
                            <!--<h1 class="form-signin-heading text-center">修改个人信息</h1> -->

                            {% for field in userprofile_form %}
                                <div class="form-group">
                                    <label class="col-md-3 control-label">{{ field.label }}</label>
                                    <div class="col-md-9">
                                        {{ field }}
                                    </div>
                                </div>
                            {% endfor %}
                            <div class="form-group">
                                <div class="col-md-4 col-md-offset-4">
                                    <button class="btn btn btn-primary btn-block" type="submit">提交</button>
                                </div>
                            </div>
                        </form>

                    </div>

              </div>

            </div>

        </div>
    </div>
   </div>



{% endblock perscontent %}

DigitalLibrary/librarian/templates/librarian/usertypeChangeinfo.html
{% extends "librarian/pers_base_ver1.html" %}
{% load staticfiles %}
{% block title %}修改个人信息{% endblock %}

{%block perscontent%}
<style>
    select, textarea, input[type="text"], input[type="password"], input[type="datetime"], input[type="datetime-local"], input[type="date"], input[type="month"], input[type="time"], input[type="week"], input[type="number"], input[type="email"], input[type="url"], input[type="search"], input[type="tel"], input[type="color"], .uneditable-input {
    -webkit-border-radius: 0;
    -moz-border-radius: 0;
    border-radius: 5px;
    width: 221px;
    height:30px;
}
</style>
 <div id="content-wrapper">

      <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">

                {% if message %}
                    <div class="alert alert-success text-center">
                        <a href="#" class="close" data-dismiss="alert">&times;</a>
                        {% if message == 'success' %}
                            <h2><a href="{%url 'readerCenter:profile'%}">修改成功,点击返回个人中心页面</a></h2>
                        {% endif %}
                    </div>
                {% endif %}

                <div class="card mb-3">
                    <div class="card-header">
                    <i></i>
                    修改用户类型信息</div>
                    <div class="card-body">
                        <form  role="form" class="form-horizontal" method="post" action="change_usertype_to_database?id={{usertype.id}}">
                            {% csrf_token %}
                            <!--<h1 class="form-signin-heading text-center">修改个人信息</h1> -->

                            {% for field in userprofile_form %}
                                <div class="form-group">
                                    <label class="col-md-3 control-label">{{ field.label }}</label>
                                    <div class="col-md-9">
                                        {{ field }}
                                    </div>
                                </div>
                            {% endfor %}
                            <div class="form-group">
                                <div class="col-md-4 col-md-offset-4">
                                    <button class="btn btn btn-primary btn-block" type="submit">提交</button>
                                </div>
                            </div>
                        </form>

                    </div>

              </div>

            </div>

        </div>
    </div>
   </div>



{% endblock perscontent %}